---
    - name: Criar Service
      template:
        src: slacko-api.service.j2
        dest: /etc/systemd/system/slacko-api.service
        owner: root
        group: root
        mode: '0755'
      register: criarservico
